### ISSUE TITLE
crashes 

### ISSUE THREAD

**Issue by Wypman1** [gurrenm3/BTD-Mod-Helper#103]
i downloaded it and am running melonloader 0.5.7 (latest version i downloaded a few days ago as of writing this) and it crashes upon loading, i always test with just mod helper and no other mods, but it keeps crashing and closing the game 

running melonloader with NO mods is working properly

also im on the newest btd6 update 

edit: trying other mods (alone and together) but its not working, problem most likely is melonloader

**Comment by xerxes93** [comment]
im also having this problem...

**Comment by windows-fryer** [comment]
Was also having this issue. Please install this version: https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.0

**Comment by Wypman1** [comment]
i installed this melonloader but it still crashes the moment i add ANY mods
in the mods folder :(
