### ISSUE TITLE
not working on latest version

### ISSUE THREAD

**Issue by mewplay123** [gurrenm3/BTD-Mod-Helper#109]
for me it does not work on melon loader and does not load in pls fix

**Comment by niemogewejsc** [comment]
same

**Comment by CactusJasper** [comment]
Are you using version 0.6.0 of melon loader with dotnet 6.0 installed

**Comment by mewplay123** [comment]
no

**Comment by mewplay123** [comment]
it only on version 5.4.0

**Comment by CactusJasper** [comment]
you should be using version 0.6 of melon loader [download here](https://github.com/LavaGang/MelonLoader/releases/download/v0.6.0/MelonLoader.x64.zip) and version 6.0 of dontnet should be installed [found here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.12-windows-x64-installer) if you get stuck with modding issues refer to [Modloader installGuide](https://hemisemidemipresent.github.io/btd6-modding-tutorial/) also be aware that version 35 of BTD6 might have broken some things
