### ISSUE TITLE
Error with v3.1.4

### ISSUE THREAD

**Issue by TheArgonaut02** [gurrenm3/BTD-Mod-Helper#114]
When I load into the game, there's a red exclamation point above the mod helper that reads:

"Failed to apply patch(es) in MenuManager_CloseCurrentMenu"
"Failed to apply patch(es) in TitleScreen_Start"

What exactly do these mean and how should I fix them? I've already uninstalled and reinstalled all mods, and have even uninstalled and reinstalled the game. I have the most recent .net file downloaded and as far as I'm concerned as long as everything here is UTD I should be too.

Any help is appreciated as I just got the game and I wanted to mod it.

**Comment by CactusJasper** [comment]
It could be the mods have not yet been updated to reflect the version 35 BTD6 update yet

**Comment by TheArgonaut02** [comment]
> It could be the mods have not yet been updated to reflect the version 35 BTD6 update yet

I haven't even installed any mods yet. Just the mod helper, unless there's some hidden update that isn't on here.

**Comment by CactusJasper** [comment]
> > It could be the mods have not yet been updated to reflect the version 35 BTD6 update yet
> 
> I haven't even installed any mods yet. Just the mod helper, unless there's some hidden update that isn't on here.
Seems like this is a mod helper issue since BTD6 only updated a few days ago to version 35 and so it might be a case of the mod helper is patching a file that has changed and so that patch is no longer applicable to how it was before
