### ISSUE TITLE
Game shut's down while loading

### ISSUE THREAD

**Issue by TheBloonsGuy** [gurrenm3/BTD-Mod-Helper#116]
Im using melon loader. When i use melon loader the game works normaly but when i add the mod helper game shut's down while loading. Thanks for help.

**Comment by doombubbles** [comment]
You'll need to provide your \BloonsTD6\MelonLoader\Latest.log file for there to be enough information to go on

**Comment by noleeeen** [comment]
I had this problem as well this is my log
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/10804835/Latest.log)

**Comment by doombubbles** [comment]
Ah well @noleeeen you're simply using a Mod Helper version that's over a year old lol. You'll need to download the latest one.

**Comment by Maxo6453** [comment]
Still occurs on latest melonloader and modhelper version.

**Comment by doombubbles** [comment]
@Maxo6453 you need to update to MelonLoader 0.6.0, more info can be found here https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Switching-to-MelonLoader-0.6.0

**Comment by TheBloonsGuy** [comment]
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/10811132/Latest.log) This is my log.

**Comment by doombubbles** [comment]
@TheBloonsGuy same issue as maxo, need MelonLoader 0.6.0 now https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Switching-to-MelonLoader-0.6.0
