### ISSUE TITLE
Despite the recent update, the button for the Mod Helper doesn't appear in the main menu whatsoever.

### ISSUE THREAD

**Issue by YetAn0therUser** [gurrenm3/BTD-Mod-Helper#118]
Exactly what it says on the tin. I'm not sure why this is, but the update didn't help. At all.

**Comment by doombubbles** [comment]
Need to see your .../BloonsTD6/MelonLoader/Latest.log file to know what the issue is. The most obvious one it could be is not using MelonLoader >0.6.0 https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Switching-to-MelonLoader-0.6.0

**Comment by DarkNebulousSpaector** [comment]
@doombubbles Melon loader does not work now :(

**Comment by DarkNebulousSpaector** [comment]
@doombubbles i have the same issue ecept that melon loader is 100% downloaded and on 0.6.0

**Comment by doombubbles** [comment]
This issue was recently fixed for another person by making sure their BloonsTD6 folder was exactly named "BloonsTD6" and not renamed to something else

**Comment by doisetheimpasta** [comment]
@doombubbles I'm on steam deck, on the latest version of BTD6 and melonloader. the folder is named BloonsTD6 exactly, and the popup before your put in the main menu (not the titlescreen) still pops up, but there is no mods menu. There is no Latest.log file.

**Comment by doisetheimpasta** [comment]
I found a way to fix it.  go to launch options and put `WINEDLLOVERRIDES="version=n,b" %command%`
