### ISSUE TITLE
Issue with 3.0.9

### ISSUE THREAD

**Issue by VideoGames1000** [gurrenm3/BTD-Mod-Helper#122]
I am very aware that I'm _probably_ an idiot in asking for help with an out-of-date hotfix, but I'm planning on using a mod that probably won't be fixed for new versions and I'm hoping someone can help me out here.
(For the record, I am using Melonloader 0.5.7 with BTD Helper 3.0.9, both very recently reinstalled with version 33.3)

The game will load as normal up until where you would traditionally get the load error (because, go figure, the game doesn't appreciate being loaded up with an out-of-date version.) The issue is that instead of the "Saving is disabled, use at your own risk" screen I'm instead greeted with the regular, unmodified new version screen. Is there a known fix for this? How reasonably doable would it be to fix this myself if I had to?

Any ideas would be greatly appreciated.

**Comment by VideoGames1000** [comment]
Also, for the record: Console screen doesn't seem to be showing any issues. Will also consult the log but expect a lot of the same.

**Comment by doombubbles** [comment]
Not sure what could really be the issue, as I'm aware of a couple other people successfully using v33 with the same overall setup you describe.
At the end of the day though, it is just a popup, and all it would actually take to "fix" it yourself would be using a tool like [Unity Explorer](https://github.com/sinai-dev/UnityExplorer) to disable the game objects whenever needed. This is a quick infographic I made a while ago on using it to play on even extremely old BTD6 versions. The same basic process should apply for v33 as well

![screenshot](https://media.discordapp.net/attachments/902619525130887220/1052333359243731044/image.png?width=1095&height=634)

**Comment by VideoGames1000** [comment]
Tested it, and no dice - Since I seem to be getting hung on the loading screen (Step 3/11 on startup) just deleting the popup doesn't seem to be allowing the game to progress. Any other ideas, or different instructions for the different context? (Also, I'm deleting the popup through InitialLoadingUI rather than title screen as, again, I don't even load to the title screen yet.)

**Comment by doombubbles** [comment]
Ah, well if you're stuck during the normal BTD6 loading steps then it sounds like something in your account profile from versions newer than v33 have made it no longer backwards compatible. Unfortunately in those instances there's not much you can do other than to have a separate account which doesn't use any newer version than the older one you're interested in
