### ISSUE TITLE
Game crashes when clicking the browse mods button

### ISSUE THREAD

**Issue by GioSalaz201** [gurrenm3/BTD-Mod-Helper#123]
After the new update I deleted and downloaded the latest version of Mod Helper but the game crashes when I click the browse mods button

**Comment by doombubbles** [comment]
Need to know what version of MelonLoader you're using and also what other mods you have. Seeing your Latest.log would also help

**Comment by GioSalaz201** [comment]
Im using v0.6.1 and i only have the mod helper mod
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/11176714/Latest.log)

**Comment by doombubbles** [comment]
Generally speaking you should keep your BloonsTD6 folder in its default install directory and not rename it to anything other than "BloonsTD6". Having that not be the case has always caused weird hard to reproduce errors for people. You can also check if there's any more crash logs in "C:\Users\gioni\AppData\LocalLow\Ninja Kiwi\BloonsTD6"

**Comment by GioSalaz201** [comment]
I moved it back to steam and i checked the latest crash
[Crash_2023-04-06_23-54-43.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/11180435/Crash_2023-04-06_23-54-43.log)

**Comment by doombubbles** [comment]
That's pretty odd, do you want to try updating your game to 36.1 ? There were a number of issues people thought were modded issues but were actually just issues with vanilla 36.0

**Comment by GioSalaz201** [comment]
I'll update it then

**Comment by Thisiswr** [comment]
Im having the same issue. How can I solve it?
