### ISSUE TITLE
Btd Mod helper has no new tower support for v36.1 yet!

### ISSUE THREAD

**Issue by Nukeman999** [gurrenm3/BTD-Mod-Helper#124]
This is a problem for other mods that have the new tower support but mod helper is still stuck on v36.0!

here's the beast handler code for the tower for the btd mod helper: https://github.com/MinecoolYT/BeastHandler/

**Comment by doombubbles** [comment]
Ok lol you're going to have to rephrase / be more specific about this my guy, I'm not sure what you're trying to say. Those jsons are generated by the Mod Helper's Export Game Data button just fine, and custom tower mods that were updated to 36.0 like Card Monkey and Temple Base continue to work on 36.1

**Comment by Nukeman999** [comment]
[Error Log for btd6 with major issues regaurding the beasthandler tower](https://cdn.discordapp.com/attachments/663099468962463765/1093686671217799219/Latest.log)

**Comment by doombubbles** [comment]
Well lol for posterity's sake I can identify that log as being not a Mod Helper or Beast Handler issue but a using the latest Ultimate Crosspathing without the latest Melon Loader 0.6.1 issue
