### ISSUE TITLE
Melonloader crashes upon trying to load BTD Mod Helper

### ISSUE THREAD

**Issue by Maxo6453** [gurrenm3/BTD-Mod-Helper#137]
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/11503488/Latest.log)

Melonloader v0.6.1 open beta
BTD Mod Helper v3.1.7
BTD6 v36.3

The game runs fine without mod helper.

I have:
Reinstalled Melonloader
Run BTD6 as administrator
Reinstalled BTD6

**Comment by crazybabyzombie** [comment]
Reinstall BTD6 on a drive with lots of free space

**Comment by JamesPL2** [comment]
I have the same thing  :( further looking for answers. Admittedly I have BTD 6 on epic games but I downloaded what you put in the plugins folder

**Comment by Jonyboylovespie** [comment]
looks like an error with your antivirus, disable it and try again
