### ISSUE TITLE
It is popping up in settings, but no mods show up. I can't modify ultimate crosspathing. 

### ISSUE THREAD

**Issue by IcyPerkz** [gurrenm3/BTD-Mod-Helper#15]
Ultimate Crosspathing works, but it's not in the mod helper settings.

**Comment by IcyPerkz** [comment]
![Screenshot 2022-02-07 225951](https://user-images.githubusercontent.com/99234000/152915759-afa8a712-1aed-4dbf-b720-855d221c2364.png)
![Screenshot 2022-02-07 230103](https://user-images.githubusercontent.com/99234000/152915852-ee5162cd-6ca2-4649-8c3d-7b06aa85228d.png)

**Comment by Mani-cwaf** [comment]
I'm also having problems with this bug also effecting save files but if you just want to change settings they are saved in text files here C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Mods\BloonsTD6 Mod Helper\Mod Settings

**Comment by doombubbles** [comment]
Closing this issue as this ought to have been fixed with v2.4.2. Please re-open this issue if it's still happening for you with the latest version

**Comment by Green-Persons** [comment]
Still Broken
