### ISSUE TITLE
everytime i luanch the gmae and try to play a map with mod helper i crash even without mods

### ISSUE THREAD

**Issue by frivll** [gurrenm3/BTD-Mod-Helper#153]
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/12111462/Latest.log)

**Comment by doombubbles** [comment]
This will be fixed in the upcoming release, until then use the actions build https://github.com/gurrenm3/BTD-Mod-Helper/suites/14263399280/artifacts/801377503

**Comment by frivll** [comment]
thank you dud i have been asking for help for 5 days lol

**Comment by frivll** [comment]
just wondering what was the proplem ?

**Comment by doombubbles** [comment]
Just a fix some people needed from having used a custom hero and then disabling it
