### ISSUE TITLE
crashes on launch steamwebveiw_onGUI

### ISSUE THREAD

**Issue by GetNoobREAL** [gurrenm3/BTD-Mod-Helper#161]
[BloonsTD6_Mod_Helper] Failed to apply BloonsTD6 Mod Helper patch(es) in SteamWebView_OnGUI: "Could not load type 'Il2CppNinjaKiwi.Players.LiNKAccountControllers.SteamWebView' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'." The mod might not function correctly. This needs to be fixed by Gurrenm4 and Doombubbles

**Comment by Jonyboylovespie** [comment]
Are you on steam?

**Comment by doombubbles** [comment]
Version 3.1.13 has fixes to not use any Steam components on the Epic Games version
