### ISSUE TITLE
Menu glitching 

### ISSUE THREAD

**Issue by HBREDER77** [gurrenm3/BTD-Mod-Helper#164]
On the main menu the button for the mod helper ui is the ui for the dart monkey and nothing happens. When i look at the maps no borders are visible. Also when i go into any difficulty it goes to easy ui and nothing shows up. when i go back into map selector i cant leave it.

**Comment by mrchunkyman** [comment]
same man idk why

**Comment by Jonyboylovespie** [comment]
In your BloonsTD6 folder there should be a folder called melonloader, inside there will be a file called latest, upload that here

**Comment by HBREDER77** [comment]
[Latest - Copy.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/12296730/Latest.-.Copy.log)

**Comment by Jonyboylovespie** [comment]
Reinstall melonloader with antivirus off

**Comment by theloganbob** [comment]
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/12304633/Latest.log)

**Comment by HBREDER77** [comment]
doesnt work for me

**Comment by doombubbles** [comment]
Closing; melonloader instalation issue
