### ISSUE TITLE
This happend when i launched bloonsTD6 with melonloader and with no mods

### ISSUE THREAD

**Issue by SamuelKing347** [gurrenm3/BTD-Mod-Helper#165]
You must install or update .NET to run this application.

App: D:\SteamLibrary\steamapps\common\BloonsTD6\BloonsTD6.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  7.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64
il2cpp_init detour failed: It was not possible to find a compatible framework version.
[07:54:21.391] [ERROR] il2cpp_init detour failed: It was not possible to find a compatible framework version.

**Comment by doombubbles** [comment]
Please go to the BTD6 Modding Discord server for general mod installation support: https://discord.com/invite/PBwGjDQ4vX
