### ISSUE TITLE
btd6 mod helper v3.1.12 is incompatible?

### ISSUE THREAD

**Issue by willywilliam1234** [gurrenm3/BTD-Mod-Helper#167]
When I launched it did play it just didn't have the mod button in the bottom right corner.
<img width="375" alt="Screenshot 2023-08-08 215131" src="https://github.com/gurrenm3/BTD-Mod-Helper/assets/141735497/85112e09-1586-4f88-b369-c7060b20bd12">

**Comment by doombubbles** [comment]
See https://github.com/GrahamKracker/BTD6EpicGamesModCompat#readme for modding the Epic Games Version
