### ISSUE TITLE
Happened when trying to launch for the first time

### ISSUE THREAD

**Issue by SilverwolfPrime** [gurrenm3/BTD-Mod-Helper#169]
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/141773023/096c77d5-8c08-4668-b420-3ad3b6c9ec09)
![Capture](https://github.com/gurrenm3/BTD-Mod-Helper/assets/141773023/dc8d3683-d16f-4656-998d-062516dc7cb8)

**Comment by doombubbles** [comment]
Please go to the BTD6 Modding Discord server for general mod setup support: https://discord.com/invite/PBwGjDQ4vX
