### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Dorian-110** [gurrenm3/BTD-Mod-Helper#175]
I am on epic games and in the game the mod is not showing and in the console it says: 'BTD6Rogue v2.0.1' is incompatible:
- BTD6Rogue is only compatible with the following Games:
- 'BloonsTD6' by Ninja Kiwi

**Comment by doombubbles** [comment]
Are you using the latest version of mod helper? It should have prompted you to download the compatibility plugin to make other mods work on Epic Games https://github.com/GrahamKracker/BTD6EpicGamesModCompat
