### ISSUE TITLE
melon loader chrashes when it tries to load this mod

### ISSUE THREAD

**Issue by asneekyrat** [gurrenm3/BTD-Mod-Helper#176]

**Comment by albertotheastraunot** [comment]
IT CRASHES FOR ULTIMATE CROSS PATHING FOR ME

**Comment by AManOfMan** [comment]
you most likely installed way too many mods for your computer to handle
Go to the mods folder and delete some less liked mods and see if that helps
Or maybe the mod wasn't updated to the new version yet

**Comment by uhagithuber** [comment]
the only mod i have is the mod helper and it crashes for some reason

**Comment by CBMBaseball03** [comment]
me too

**Comment by 12333ffd** [comment]
try turning off real time scan and re install melon loader and it fixes!
