### ISSUE TITLE
Epic Compat Broken

### ISSUE THREAD

**Issue by haiku-balls** [gurrenm3/BTD-Mod-Helper#177]
Through the game, downloading the Epic Games Compatibility dll doesn't work.
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/65756037/e309ddc6-f226-48c2-b6e6-fa153ebc494a)
It downloads a dummy file (being 1KB) and after relaunching it prompts to download again. Trying to download it from github just throws a [404](https://github.com/GrahamKracker/BTD6EpicGamesModCompat).

**Comment by doombubbles** [comment]
GrahamKracker is dealing with some account issues at the moment and it should hopefully be resolved before too long

Until then, here's the most recent version I have

[BTD6EpicGamesModCompat.zip](https://github.com/gurrenm3/BTD-Mod-Helper/files/12544216/BTD6EpicGamesModCompat.zip)

**Comment by haiku-balls** [comment]
I see. Thanks :p

**Comment by haiku-balls** [comment]
He seems to have resolved his account problems.
