### ISSUE TITLE
what is .NET 6.0

### ISSUE THREAD

**Issue by Serpience** [gurrenm3/BTD-Mod-Helper#178]
It says i dont have .NET 6.0 installed. What is this?

**Comment by doombubbles** [comment]
You need a newer version of Microsoft's .NET runtime than what your computer currently has installed 

https://dotnet.microsoft.com/en-us/download/dotnet/6.0

For 64bit windows you'd most likely want this one https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.21-windows-x64-installer
