### ISSUE TITLE
When ever I use any mod, it won't let me load into BTD6 and it crashes when I press start .

### ISSUE THREAD

**Issue by 1DoesEverything** [gurrenm3/BTD-Mod-Helper#18]
I have even tried the new btd6 mod loader, but still and i have just used btd6 mod helper but it will only crash

**Comment by ricorod** [comment]
i have the same problem it freezes the game when trying to check for updates for me.

**Comment by doombubbles** [comment]
Sorry for the late response, but I've fixed this problem as far as I'm aware in the versions since this issue was created. Def reopen if I'm mistaken.
