### ISSUE TITLE
Downloaded everything correctly, but the mod button isn't showing up

### ISSUE THREAD

**Issue by MrMinerria** [gurrenm3/BTD-Mod-Helper#181]
I have the latest version of the microsoft thing, melonloader and modhelper, but the button for mods still isn't showing up, can someone please help me?

**Comment by MisterAwesome0440** [comment]
hey so I guess GitHub is shadow banning the creators of the mod, why? no clue. but on the discord they have this link to get yourself up and running again, but make sure to follow the guide exactly! https://github.com/Onixiya/btd6-modding-tutorial

**Comment by MrMinerria** [comment]
does this explain about why the mod button isnt showing up? i read through it quickly and followed the instructions, but its still bugged, and yes i have made 110% sure everything is the exact same as the tutorial and up to date, even following multiple different tutorials
as well as checking my antivirus software to restore any auto removed files
and making sure the game is up to date

**Comment by MrMinerria** [comment]
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/144787380/e63c3970-5559-4d00-8b14-6b21f71ba417)
this is the melon loader thing too, is this a worry, saying its missing dependencies?

**Comment by MisterAwesome0440** [comment]
I had to delete everything and restart completely with that link I sent you to get it to work and then the mods button showed up. Also check out the discord if you need anymore help that's where I found out this.  https://discord.gg/ENutspCb

**Comment by MrMinerria** [comment]
so
i stopped my antivirus, then it worked, but when i reactivated it, it stopped fricken working again

**Comment by MrMinerria** [comment]
accidentally closed it

**Comment by MrMinerria** [comment]
and is it bad that my antivirus is detecting a heuristic virus within this???

**Comment by doombubbles** [comment]
Sounds like you just have a particularly zealous anti-virus that is giving false positives on MelonLoader, unfortunately there's nothing more we can do for you about that beyond you adjusting your own settings for it.

**Comment by MrMinerria** [comment]
aight, thanks for the help, i will change my antivirus to stop being a feckin bastard
