### ISSUE TITLE
game crashes after loading

### ISSUE THREAD

**Issue by randomguy45672** [gurrenm3/BTD-Mod-Helper#186]
![issue](https://github.com/gurrenm3/BTD-Mod-Helper/assets/147902381/fbb294a8-6173-4396-9713-7c9067d956f3)
every time i load the game it just says this i tried reinstalling everything and running as administrator but it keeps saying this and i also have net 6.0 in the runtimes folder

**Comment by TrueJugg** [comment]
I have a same problem but mine doesn't even show any error and after a while i can launch the game again and same thing continues.
![obrázek_2023-10-15_005917129](https://github.com/gurrenm3/BTD-Mod-Helper/assets/147953511/96f47bb5-bbcd-4c78-9d0d-acc7d3a7b833)

**Comment by Coriandre450** [comment]
I have the same issue as TrueJugg anyone knows how to resolve the issue?
