### ISSUE TITLE
bloons td6 not working

### ISSUE THREAD

**Issue by ItsLLolly** [gurrenm3/BTD-Mod-Helper#187]
hello i have recently started btd6 and tried to download mods (i use melonloader) and everytime i tried to start it it says:
internal failure
ilc2cpp_init detour failed: failed to load hostfxr. please make sure u have .net 6.0 runtime
pls help

**Comment by Nightgamer4768** [comment]
ciao, ho provato ha far partire btd6 (con melonloader) e mi diceva "errore assicurati di avere installato net 6.0 non è possibile aprire bloons tower defense 6" però ho fatto esattamente cosa c'era scritto di fare e non ho idea di cosa sia net 6.0

**Comment by 32QWREA** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0 download the runtime thing from here it should work
