### ISSUE TITLE
Is the most recent change going to get my acc flagged by default?

### ISSUE THREAD

**Issue by OneBitOfHope** [gurrenm3/BTD-Mod-Helper#19]
This isnt exactly a bug but more so a major question, I really dont wanna get my acc flagged and want to make sure forcing the game to save progress wont get me banned

**Comment by doombubbles** [comment]
I can't give you any guarantees, but the mod helper already has been stopping non-cheaty mods like custom towers from making permanent / noticeable marks on your profile. I'd be surprised if you got flagged now for doing something that you'd already been doing before without getting flagged. Though I'll probably add a toggle for this progress saving feature for those who are worried.
