### ISSUE TITLE
cant find mods tab and when i install mods and mods wont load when i install them manually

### ISSUE THREAD

**Issue by researchertoast** [gurrenm3/BTD-Mod-Helper#194]
so i open the game and i cant find the mods tab and when  i add mods to the melonloader 0.6.1 the mods dont load i use melonloader 0.6.1 x86

**Comment by CBMBaseball03** [comment]
yeah me too

**Comment by hiyyyme** [comment]
well mods work for me but i dont have the mods tab, if you guys are on epic games version then install the epic games compatability plugin too
