### ISSUE TITLE
After update  v3.1.16, the mod helper button doesnt work, and has the wrong image.

### ISSUE THREAD

**Issue by AkitaEllie** [gurrenm3/BTD-Mod-Helper#197]
Environment details : Windows 11, build 23590
Game from : Epic games
Installed mods : BTD6 mod helper, FasterForward, AutoEscape
Installed plugins : BTD6EpicGamesModCompat
Reproducing steps :
Update from last version, restart, and see :
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/80521057/e7c48bc1-beb7-4731-bd28-bb398715421c)

**Comment by AkitaEllie** [comment]
forgot to attach : the terminal 
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/80521057/5709cb33-fd56-4bf3-8c99-49ee54e0af22)

**Comment by doombubbles** [comment]
Keep using the previous version https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.15 until update 40 releases for Epic Games

**Comment by AkitaEllie** [comment]
Thank you, and i just received update 40, seems to be fixed
