### ISSUE TITLE
 il2cpp_init detour failed: It was not possible to find a compatible framework version.

### ISSUE THREAD

**Issue by Msteenfat** [gurrenm3/BTD-Mod-Helper#198]
il2cpp_init detour failed: It was not possible to find a compatible framework version. 
What do i do?

**Comment by thatguy0123** [comment]
how do i fix this? i have the same problem, and i see you closed it but im still wondering on how to fix

**Comment by doombubbles** [comment]
You'll want to download .NET runtime 6.0+ https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.29-windows-x64-installer
