### ISSUE TITLE
saving issue ingame

### ISSUE THREAD

**Issue by Spieky** [gurrenm3/BTD-Mod-Helper#20]
i was playing lych, got to r60~, moab about to leak so I backed out of the game and went back in. but when I got back in I was back at like r13. idk why this happened and its definitely not because of anything else

**Comment by Mani-cwaf** [comment]
> i was playing lych, got to r60~, moab about to leak so I backed out of the game and went back in. but when I got back in I was back at like r13. idk why this happened and its definitely not because of anything else

it's because btd6 doesn't let you save with mods now, it was supposed to be fixed with the new mod helper version but it wasn't

**Comment by doombubbles** [comment]
Boss saving was working the last time I checked, so I'm closing this issue for now
