### ISSUE TITLE
.net 6.0 error

### ISSUE THREAD

**Issue by lpb2050** [gurrenm3/BTD-Mod-Helper#200]
i have .net 6.0 runtime but it keeps giving me the error
![Screenshot (7)](https://github.com/gurrenm3/BTD-Mod-Helper/assets/155052412/baad2416-7512-4718-b367-c647edb50965)

**Comment by JustAFellowGal** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.418-windows-x64-installer
install this
(yes this is from official microsoft website)

**Comment by doombubbles** [comment]
net6 installation issue, redownload and also restart computer https://dotnet.microsoft.com/en-us/download/dotnet/6.0
