### ISSUE TITLE
for some reason its crashing my game

### ISSUE THREAD

**Issue by uhagithuber** [gurrenm3/BTD-Mod-Helper#201]
I don't know why its crashing my game

**Comment by uhagithuber** [comment]
the message it gave me 
![Screenshot (2)](https://github.com/gurrenm3/BTD-Mod-Helper/assets/155186899/8a0ef612-f8cc-44e0-a9d8-bcd5f3920519)

**Comment by 32ewfdsf** [comment]
This is exactly what happened to me lol

**Comment by uhagithuber** [comment]
lol

**Comment by uhagithuber** [comment]
@doombubbles i need help

**Comment by uhagithuber** [comment]
@everyone

**Comment by doombubbles** [comment]
You should try uninstalling and reinstalling MelonLoader through its installer

**Comment by uhagithuber** [comment]
oh thank you

**Comment by uhagithuber** [comment]
sadly its still happening

**Comment by doombubbles** [comment]
Other things you could try are making sure the file name doesn't have the (2) in it, and also checking your antivirus settings and possibly disabling it while installing melonloader. That error message indicates that there's a problem with the main code assembly that MelonLoader is supposed to generate, so it may be getting blocked

**Comment by uhagithuber** [comment]
huh?
i dont see it with my antivirus

**Comment by uhagithuber** [comment]
i still cant solve it/

**Comment by GalexGX** [comment]
Apparently MelonLoader is searching for "Assembly-CSharp" with an empty version?
First time i see this issue, kinda weird.
Try installing a full .NET 6 SDK, instead of just Runtime.

**Comment by uhagithuber** [comment]
it only happens when i have this mod? how?

**Comment by uhagithuber** [comment]
i checked and its not empty?

**Comment by uhagithuber** [comment]
i tried the newest version
idk how to fix it its still happening

**Comment by uhagithuber** [comment]
i got it fixed i just turned off my anto virus then install it again and boom its working!
