### ISSUE TITLE
Mod Loader .dll not letting btd6 open.

### ISSUE THREAD

**Issue by 32ewfdsf** [gurrenm3/BTD-Mod-Helper#202]
Whenever I try to open BTD6 with MelonLoader it normally works fine, but whenever I add the Modloader.dll file, it decides not to open and randomly closes halfway through opening. Hope you can fix this or tell me how to fix this, because I am stupid. Thanks.

![Screenshot 2023-12-29 160531](https://github.com/gurrenm3/BTD-Mod-Helper/assets/155189031/0e0c15fe-dd5c-4981-b412-c7be141df244)

**Comment by uhagithuber** [comment]
hi

**Comment by lawley21** [comment]
Does someone know how to fix this? game loads fine without mods but the moment i put them in the mod folder it wont start the game

**Comment by milk98123** [comment]
i have this error too

**Comment by TheBlock7686** [comment]
my exact problem aswell please give a solution

**Comment by CBMBaseball03** [comment]
Me too nobody responds ever
