### ISSUE TITLE
my game gets to just before the melon loader progress bar and crashes.

### ISSUE THREAD

**Issue by 32QWREA** [gurrenm3/BTD-Mod-Helper#205]
I have no mods installed. How do i fix this because if I can't than it's a waste of over 30$

**Comment by GalexGX** [comment]
1. BTD6 or/and MelonLoader don't cost 30$, don't tell me you bought monkey money in that game.
2. If your issue resists after every troubleshooting step, you can just delete MelonLoader with this guide: https://github.com/LavaGang/MelonLoader#un-install
3. Provide extra details. Nobody can help you if you provide no details to your issue, e.g. the melonloader logs/console
