### ISSUE TITLE
Crash on new profile

### ISSUE THREAD

**Issue by millefoleon** [gurrenm3/BTD-Mod-Helper#21]
Using the mod on a new profile (that transitions to the tutorial game) crashes the client after the welcome screen.
Removing the mod lets you play the tutorial but after version 30 the game does not save the progress so you are stuck in a tutorial loop.

To replicate issue: Start a new profile with the mod + melon loader installed.

Workaround: Reinstall the game, finish the tutorial then install mod helper and melon loader.

**Comment by doombubbles** [comment]
Closing for now as the other ProfileModel validation fixes that have happened seemed to have fixed this as well, at least for me. If you get the issue again re open this and attach your BloonsTD6/MelonLoader/Latest.log file
