### ISSUE TITLE
Mod-Helper not responding

### ISSUE THREAD

**Issue by Red0ni** [gurrenm3/BTD-Mod-Helper#211]
I have Mod helper in my files and its not working

![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/157087889/be437f30-abc6-43df-9da0-77aa46f906eb)

![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/157087889/15f997e4-b826-4843-8510-8cd7212dca57)

**Comment by OrionLima** [comment]
I think it's because it's has (3) and (1)

**Comment by CBMBaseball03** [comment]
Did you ever figure this out it doesnt work for me either
