### ISSUE TITLE
I Made a Mod but it's not showing up in the BTD Mod Browser Website or The In-Game Browser

### ISSUE THREAD

**Issue by OrionLima** [gurrenm3/BTD-Mod-Helper#212]
Hey, Orion Here
I recently created a mod (https://github.com/OrionLima/FirstMod),  I have all the right tags and topics but, I can't seem to find it on the browser, is it because I just got into modding and you need to verify or what?
Please fix this issue.
Thank You,
Orion Lima

**Comment by doombubbles** [comment]
First try using only the `btd6-mod` topic on your repository and not also the `btd6-mods` topic, and updating your [ModHelperData.cs](https://github.com/OrionLima/FirstMod/blob/main/ModHelperData.cs#L10) to have the correct Repository Name
But yes, people would need to have the Show Unverified Mods setting enabled to see unverified mods

**Comment by OrionLima** [comment]
Thanks for the info

**Comment by OrionLima** [comment]
Doombubbles,
The mod still does not show up in the mod browser,
I did everything you told, however, it  still wont appear
In the console it shows this error (Attached Here)
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/159525795/2914ca8b-8dbe-4eaf-8f9d-8921090f6cd7)
Even though ModHelperData.cs(https://github.com/OrionLima/FirstMod/blob/main/ModHelperData.cs#L10)) is correct (The ModHelperData.cs(https://github.com/OrionLima/FirstMod/blob/main/ModHelperData.cs#L10)) is attached here) 
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/159525795/25a53fa2-4a21-4a1b-9fae-3e8e011fa550)

**Comment by OrionLima** [comment]
> Doombubbles, The mod still does not show up in the mod browser, I did everything you told, however, it still wont appear In the console it shows this error (Attached Here) ![image](https://private-user-images.githubusercontent.com/159525795/303904062-2914ca8b-8dbe-4eaf-8f9d-8921090f6cd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzY1MjgsIm5iZiI6MTcwNzYzNjIyOCwicGF0aCI6Ii8xNTk1MjU3OTUvMzAzOTA0MDYyLTI5MTRjYThiLThkYmUtNGVhZi04ZjlkLTg5MjEwOTBmNmNkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNzIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODg4MTM5N2Y2ZTE0Njk0NTc4ZWFkMmYyZDI3MDI5ODU5YjA5ZjIzZjAwNTVjZTZlM2M2NThjNzE0YzQxMGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.67tYH6Nh9JP6zWkM_wWruAzDOvyS9tPWOnISINRMdhk) Even though [ModHelperData.cs](https://github.com/OrionLima/FirstMod/blob/main/ModHelperData.cs) is correct (The [ModHelperData.cs](https://github.com/OrionLima/FirstMod/blob/main/ModHelperData.cs) is attached here) ![image](https://private-user-images.githubusercontent.com/159525795/303904135-25a53fa2-4a21-4a1b-9fae-3e8e011fa550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzY1MjgsIm5iZiI6MTcwNzYzNjIyOCwicGF0aCI6Ii8xNTk1MjU3OTUvMzAzOTA0MTM1LTI1YTUzZmEyLTRhMjEtNGExYi05ZmFlLTNlOGUwMTFmYTU1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwNzIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmU2ODVmY2Q4YTY2YTQxMDhkYWFlYzI5NDU3MDM5ZDFhOTQ0ZWUxNzA4MzQwMTkyNTc4MjFjMTkzNzNkZDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FA8ch-jHbEzYDEw8tP2YCDploXk6y9LsQRGSYqUkseY)

My Only Guess is that it's picking up my other repository instead of the new one due to me making 2 repositories to trying to trobleshoot the issue but in my first repository I had the mod in a folder rather than directly in the main branch.

**Comment by OrionLima** [comment]
So I finally resolved the issue but I had to completely rewrite all of the code.
Well that was fun...

**Comment by OrionLima** [comment]
Also "RepoName" doesn't do anything as I called it "BetterMonkeyAce" but my actual RepoName is [Monkey-Ace-But-Better](https://github.com/OrionLima/Monkey-Ace-But-Better/tree/main)
