### ISSUE TITLE
loader gives error that i dont know how to fix.

### ISSUE THREAD

**Issue by milk98123** [gurrenm3/BTD-Mod-Helper#213]
when i try to load it this error shows up ![Screenshot (3)](https://github.com/gurrenm3/BTD-Mod-Helper/assets/159739949/4376c9f8-3068-4b64-b905-9ba35028145e)
5e)

**Comment by milk98123** [comment]
its solved

**Comment by rgamer82** [comment]
Hi, do you know how you solved this?
