### ISSUE TITLE
mods menu button missing

### ISSUE THREAD

**Issue by otherlabel** [gurrenm3/BTD-Mod-Helper#217]
the mod menu button is replaced with the "monkeys" menu button and its half cut off the screen however it only appears after clicking play twice and exiting out of play menu. I found that mods still work even when mod helper isn't working but mods that create new towers do not i have installed .NET 6.0 it says im missing "Il2CppFacepunch.Steamworks" and i have reinstalled the latest version with anti virus off I need help

**Comment by Thatonekid47** [comment]
same thing is happening with me however i cannot even get it to show up when i click play

**Comment by casebip** [comment]
same

**Comment by creepr967Gamer** [comment]
It didn't appear at all when i loaded up the game it just said some modes can't be used
