### ISSUE TITLE
The game crashes when i put the Mod Helper in the mods folder

### ISSUE THREAD

**Issue by CBMBaseball03** [gurrenm3/BTD-Mod-Helper#222]
When i put the mod helper in the folder it has an error and closes and it ends in a 75 but i dont have enough time to read it before it closes.

**Comment by CBMBaseball03** [comment]
![image_2024-03-22_091221137](https://github.com/gurrenm3/BTD-Mod-Helper/assets/164504738/601a7ab1-3274-489d-a739-0fcccf754e4d)

**Comment by CBMBaseball03** [comment]
Or any other mod please help i am urgent

**Comment by doombubbles** [comment]
https://gurrenm3.github.io/BTD-Mod-Helper/wiki/Install-Guide#missing-assembly-charpdll

MelonLoader didn't install correctly, may need to turn off your antivirus when installing it

**Comment by Symmettry** [comment]
ty

**Comment by TurtleLegend64** [comment]
yea all the files get downloaded but it just crashes melonloader and bloons.

**Comment by Symmettry** [comment]
auto-closing is an awful thing. the issue isn't fixed just because it's taken a long time to get a response.

**Comment by Symmettry** [comment]
> > auto-closing is an awful thing. the issue isn't fixed just because it's taken a long time to get a response.
> 
> I can see where you're coming from, but in this case
> 
> 1. This issue did get a response
> 2. This issue was not even a Mod Helper issue, it was a MelonLoader installation issue
> 3. The standard solution to this issue is already listed in the install guide
> 
> Without the bot I would probably just be closing issues like these myself even sooner. A lot of issue posters would likely be better off just getting real time back and forth help in the btd6 modding Discord server.
yeah, it should've been closed already if it wasn't an issue is my point.

autoclosing doesn't make issues go away, and so it should never be on
