### ISSUE TITLE
.NET 6.0 runtime error, can't open BTD6

### ISSUE THREAD

**Issue by LoafOfLogAnd** [gurrenm3/BTD-Mod-Helper#223]
Every time I open BTD6 I get this. I just installed melon loader into the BTD6 file and put the dll and xml mod helper files in the mod file but now I always get this and don't know what to do.
<img width="1002" alt="image" src="https://github.com/gurrenm3/BTD-Mod-Helper/assets/147915128/910ebb49-3547-40a5-9998-77ee3288809a">

**Comment by piskotcz** [comment]
i have this problem too

**Comment by LoafOfLogAnd** [comment]
Thank you.
