### ISSUE TITLE
Hello, i have a problem with mod helper

### ISSUE THREAD

**Issue by CONSTRUCTORUL** [gurrenm3/BTD-Mod-Helper#228]
Failed to apply BloonsTD6 Mod Helper patch(es) in TowerPurchaseButton2D_DetermineBackgroundSprite: "Could not load type 'Il2CppAssets.Scripts.Utils.SpriteReference' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'." The mod might not function correctly. This needs to be fixed by Gurrenm4 and Doombubbles

this is the error please help me. All my mods are gone.

**Comment by doombubbles** [comment]
You should manually download the latest version of Mod Helper https://github.com/gurrenm3/BTD-Mod-Helper/releases/latest
