### ISSUE TITLE
how do i make it so i have 2 instances of btd6 with seperate save files on the same computer i want a modded and unmodded one

### ISSUE THREAD

**Issue by bombaatomowa123456** [gurrenm3/BTD-Mod-Helper#229]

**Comment by diamentxd4661** [comment]
if you have the steam version then right click on btd6 then find "show local files" then back once, copy the btd6 folder and paste it where you want and make melonloader prep the copied one

**Comment by bombaatomowa123456** [comment]
but i dont want my save file to get flagged i want seperate save
