### ISSUE TITLE
it says compatible framework version

### ISSUE THREAD

**Issue by Shibelordthegod** [gurrenm3/BTD-Mod-Helper#233]
![image_2024-05-08_160010567](https://github.com/gurrenm3/BTD-Mod-Helper/assets/169314304/48b1bdd3-4405-483a-a0cf-a15afeeed41e)
# Bug

**Comment by doombubbles** [comment]
Please refer to the Install Guide for downloading .net 6.0 https://gurrenm3.github.io/BTD-Mod-Helper/wiki/Install-Guide#troubleshooting
