### ISSUE TITLE
API not loading, no mods with this dependency are working. 

### ISSUE THREAD

**Issue by XenonZe** [gurrenm3/BTD-Mod-Helper#24]
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/8366788/Latest.log)

**Comment by Green-Persons** [comment]
I am having the same issue

**Comment by doombubbles** [comment]
I've still not been able to reproduce this specific VTable setup error. If using the latest version of the Mod Helper doesn't work, then I'd need to see screenshots of your Mods folder and overall BloonsTD6 folder. You could also try reinstalling MelonLoader in the mean time.

**Comment by bob1322** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/107728467/174409807-ab49f427-0d9f-4967-8b74-707887567d18.png)

**Comment by bob1322** [comment]
this is what happens when I try to load mod helper

**Comment by LopyLuna** [comment]
I got the same too
