### ISSUE TITLE
Error: "Failed to apply BloonsTD6 Mod Helper patch(es)"

### ISSUE THREAD

**Issue by interpolation-0** [gurrenm3/BTD-Mod-Helper#240]
# Bug

### Game Version

v41.2

### MelonLoader Version

v0.6.2

### Mod Helper Version

v3.1.21 latest as of june 5th, 2024

### Description

The "Mods" button does not appear
The monkeys menu is broken
![image](https://github.com/gurrenm3/BTD-Mod-Helper/assets/154097616/242c56f6-f85b-46ca-8584-10ae3dc75a20)
Clicking the back button on the monkeys menu crashes the game
All monkeys in game are invisible
![image](https://interpolations.questionable.link/6CuzEenf3.gif)

### Logs

[during round.log](https://github.com/user-attachments/files/15592377/during.round.log)
[monkeys menu.log](https://github.com/user-attachments/files/15592411/monkeys.menu.log)
after and before step 9 are actually meant to be after and before clicking the start button.

**Comment by doombubbles** [comment]
Using the latest version of Mod Helper for older versions of the game like v41 is almost always going to have issues like this and can't be avoided. You should update your game through Steam / Epic
