### ISSUE TITLE
my mod button is gone

### ISSUE THREAD

**Issue by Thetruewatergod** [gurrenm3/BTD-Mod-Helper#242]
my whole mod button is gone

**Comment by cactusreel123324** [comment]
open melon loader and downgrade the mods version to v6.1

**Comment by doombubbles** [comment]
Being on the wrong MelonLoader version will now be a more clear error in the latest Mod Helper version https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.25
