### ISSUE TITLE
can't change mod settings 

### ISSUE THREAD

**Issue by diamentxd4661** [gurrenm3/BTD-Mod-Helper#246]
# Bug 

### Logs

<!-
[Latest.log](https://github.com/user-attachments/files/16057649/Latest.log)
- -->

**Comment by diamentxd4661** [comment]
things broke and this empty now except the log file :p

**Comment by diamentxd4661** [comment]
melon loader version 0.6.3 
game version 43.3.8118
mod helper version idk latest as of 01.07.2024
description when i change things in mod settings they don"t change when i reboot the game

**Comment by jlin368** [comment]
You have to downgrade Melonloader to 0.6.2. For some reason, Melonloader version 0.6.3 and up deletes the data in the Mod Settings files and causes a lot of mods to break.

**Comment by doombubbles** [comment]
Being on the wrong MelonLoader version will now be a more clear error in the latest Mod Helper version https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.25
