### ISSUE TITLE
Game does not launch

### ISSUE THREAD

**Issue by Hexecutabl3** [gurrenm3/BTD-Mod-Helper#247]
# Bug

### Game Version

43.3.8118

### MelonLoader Version

6.1

### Mod Helper Version

newest

### Description
The game does not launch melonloader shows no errors
![image_2024-07-06_213126674](https://github.com/gurrenm3/BTD-Mod-Helper/assets/174900614/597c9761-79ab-40cd-82b0-34cf4104a108)

**Comment by Justyouraveragelunatic** [comment]
idk how to fix this but try to uninstall and redownload melon launcher.
