### ISSUE TITLE
Game crashes when i try to place custom towers

### ISSUE THREAD

**Issue by 616-com** [gurrenm3/BTD-Mod-Helper#248]
# My game crashes when i try to place custom towers

### Game Version

43.0

### MelonLoader Version

0.6.4

### Mod Helper Version

3.1.21

### Description

So i was downloading mods for btd6, and when i try to place any custom tower, even the ones that have been upgraded for 43.0, my game simply crashes, and that happens with all custom towers, idk why that keeps happening...

### [Logs](https://github.com/user-attachments/files/16120940/Latest.log)
(im using the missile monkey in here for example, which is the first custom tower that appears on recently updated and with all other mods disabled except for btd6 mod helper and rate changer which for some reason wasn't disabled)

**Comment by jlin368** [comment]
Try downgrading Melonloader to 0.6.2. For some reason, Melonloader version 0.6.3 and up deletes the data in the Mod Settings files and causes a lot of mods to break.

**Comment by scrambldchannel** [comment]
Thanks @jlin368, I can confirm this fixed the same issue in my case. This has made a ten year old very happy but also unwilling to go to bed ;)

**Comment by doombubbles** [comment]
Being on the wrong MelonLoader version will now be a more clear error in the latest Mod Helper version https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.25

**Comment by TlGOo** [comment]
@jlin368 My brother installed everything for me so idk how to downgrade...
