### ISSUE TITLE
bloons td 6 crashes when i put down custom towers

### ISSUE THREAD

**Issue by scottymedflosshatt** [gurrenm3/BTD-Mod-Helper#252]
# Installation Error

**Comment by Random11210** [comment]
Same thing happens to me, let me know when you find a bug fix.

**Comment by doombubbles** [comment]
Ensure that you're on MelonLoader 0.6.1, and if not then try downgrading to that via the installer. It remains the most stable version for BTD6 use

**Comment by lewluuuu** [comment]
@doombubbles how do you downgrade btd6 though?

**Comment by lewluuuu** [comment]
@doombubbles I can't find out how to downgrade btd6

**Comment by doombubbles** [comment]
This will now be a more clear error in the latest Mod Helper version https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.25
