### ISSUE TITLE
its saying "Failed to apply patch(es) in: ..."

### ISSUE THREAD

**Issue by DrMilkMan56** [gurrenm3/BTD-Mod-Helper#257]
# Bug

### Game Version

44.0

### MelonLoader Version

V0.6.4

### Mod Helper Version

V3.1.23

### Description

i tried booting up btd6 after the newest update (seamonkey addition) and then the game didnt load, so i tried re-installing modhelper and then it worked, but i was struck with a warning i havent seen before, it said something among the lines of: "you are using mods, and your account might get flagged, so its best to go on a different account if you want to mod" and then gave me the option to continue using this account, to select a different one or to leave the game, i clicked continue and saw that theres a red exclamation mark on my mod helper, i clicked it and then it showed me this
![doesnt work lol](https://github.com/user-attachments/assets/834b661f-4e96-4f41-8872-e4dd27793b8a)

**Comment by doombubbles** [comment]
These were some false errors for the Epic Games client that will no longer appear in the latest Mod Helper version https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.25
