### ISSUE TITLE
Game stuck on loading screen

### ISSUE THREAD

**Issue by Pokemaster1278** [gurrenm3/BTD-Mod-Helper#259]
# Bug

### Game Version

44.1.8303

### MelonLoader Version

v0.6.1

 Mod Helper Version

v3.1.21

### Description

![image](https://github.com/user-attachments/assets/11b060f5-f866-4cca-bd77-6300b2a57364)
 my game is stuck on the loading screen

### Logs

[Latest.log](https://github.com/user-attachments/files/16741200/Latest.log)

**Comment by doombubbles** [comment]
Just need to download the latest version from GitHub https://github.com/gurrenm3/BTD-Mod-Helper/releases/latest/download/Btd6ModHelper.dll
