### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by juicee725** [gurrenm3/BTD-Mod-Helper#263]
# Installation Error

### Game Version

Steam 

v0.6.4 MelonLoader Version

3.2.0 Mod Helper Version

When starting the game via the desktop shortcut or the steam app this message is in place of all the code usually seen when running:

" il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime.
[10:32:34.221] [ERROR] il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime. "

### Logs
[Latest-Bootstrap.log](https://github.com/user-attachments/files/16835702/Latest-Bootstrap.log)

**Comment by juicee725** [comment]
Please Help

**Comment by doombubbles** [comment]
https://gurrenm3.github.io/BTD-Mod-Helper/wiki/Install-Guide#internal-failure--il2cpp_init_detour--net-60-runtime
It's telling you that you need to install the .NET 6.0 Runtime https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.29-windows-x64-installer

**Comment by juicee725** [comment]
Thank you so much
