### ISSUE TITLE
bug error by installing mod helper dll

### ISSUE THREAD

**Issue by Proplayer5ty** [gurrenm3/BTD-Mod-Helper#266]
# Bug
The game says thath unknown version and I am using a mod helper dll its crasshing and if i didn't go to the folder and add the mod helper dll its normaly game but with no mods any ideas how i can fix thath?

bloon td 6 version:44.1
[BTD-Mod-Helper-3.2.1.zip](https://github.com/user-attachments/files/16946353/BTD-Mod-Helper-3.2.1.zip)

Mod Helper Version 3.2.1

**Comment by doombubbles** [comment]
What you linked there is the source code for Mod Helper, to actually use it in game you need to download the compiled .dll and put that in your mods folder https://github.com/gurrenm3/BTD-Mod-Helper/releases/latest/download/Btd6ModHelper.dll
