### ISSUE TITLE
failed to apply patch(es) in timemanager_maxsimulaionstepsperupdate

### ISSUE THREAD

**Issue by Bosyara** [gurrenm3/BTD-Mod-Helper#276]
# Bug

### Game Version

45.2.8529

### MelonLoader Version

0.6.5

### Mod Helper Version

3.3.0

### Description

Yesterday everything was fine, and I was playing with these mods, but today I logged into the game and they stopped working.

### Logs

[Latest.log](https://github.com/user-attachments/files/17411392/Latest.log)

![image](https://github.com/user-attachments/assets/0d91500f-af0d-490f-b70b-b608ed153ab6)

**Comment by CaioBreak** [comment]
got the same error

**Comment by doombubbles** [comment]
New build for v45.2 https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.3.1
