### ISSUE TITLE
Mod Helper Doesnt Work

### ISSUE THREAD

**Issue by GokuUchihaDLuffy** [gurrenm3/BTD-Mod-Helper#28]
it doesnt work at all, the mods dont work

**Comment by doombubbles** [comment]
To help I'd need at least as much info as in https://github.com/gurrenm3/BTD-Mod-Helper/issues/32 i.e. the BloonsTD6/MelonLoader/Latest.log file, a screenshot of your Mods folder and preferably also a screenshot of your BloonsTD6 folder. We'll get this put in an issue template.
