### ISSUE TITLE
Mod options window empty

### ISSUE THREAD

**Issue by AltoidDev** [gurrenm3/BTD-Mod-Helper#32]
When I click on the mod options window in BTD6 there is nothing there, despite me having temple sacrifice helper installed.
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/8548385/Latest.log)
![Screenshot 2022-04-23 115926](https://user-images.githubusercontent.com/100539243/164942699-6b2fc4d0-4021-40f8-bcf0-5ba93aff7137.png)
![Screenshot 2022-04-23 115859](https://user-images.githubusercontent.com/100539243/164942703-d626a9f6-4269-435e-958c-f7348dbf1554.png)

**Comment by doombubbles** [comment]
From your log I see you were using Mod Helper version 2.4.7, does the issue still persist with 2.4.8? If so it would also be helpful if you could trial and error somewhat to see which mods in particular cause this error to arise.
