### ISSUE TITLE
API doesn't load, also mods that depend on the helper do not load

### ISSUE THREAD

**Issue by KeeveeKoomoo** [gurrenm3/BTD-Mod-Helper#33]
So, a lot of people here have this problem, yet nobody has been answered. I, and everybody else, would really appreciate, at least closure, that you recognise the problem exists, so that we know it is being worked on.

**Comment by doombubbles** [comment]
To help I'd need at least as much info as in #32 i.e. the BloonsTD6/MelonLoader/Latest.log file, a screenshot of your Mods folder and preferably also a screenshot of your BloonsTD6 folder. We'll get this put in an issue template.
