### ISSUE TITLE
My towers icons are broken

### ISSUE THREAD

**Issue by SirBlueAxolotl** [gurrenm3/BTD-Mod-Helper#34]
Here is the broken towers ![image](https://user-images.githubusercontent.com/105134703/167276379-d317739b-2b4c-4e3b-9e43-d55f61255a88.png)
My mods:
![image](https://user-images.githubusercontent.com/105134703/170495200-61b445a2-3d8a-4703-a9d9-deb87600fed0.png)

**Comment by SirBlueAxolotl** [comment]
Btw it's just the icons

**Comment by GooUckd** [comment]
It's probably because of the new game update.
the API hasn't been updated yet..

**Comment by SirBlueAxolotl** [comment]
> It's probably because of the new game update. the API hasn't been updated yet..

ok

**Comment by doombubbles** [comment]
Can you double check that you're using the latest version of the Mod Helper, v2.4.8? I've seen this bug a couple of times before (prior to this update) and it's just been from people using an older version. You can upload the BloonsTD6/MelonLoader/Latest.log file.

**Comment by SirBlueAxolotl** [comment]
> Can you double-check that you're using the latest version of the Mod Helper, v2.4.8? I've seen this bug a couple of times before (prior to this update) and it's just been from people using an older version. You can upload the BloonsTD6/MelonLoader/Latest.log file.

Yes I'm using v2.4.8 I can't find Latest.log file

**Comment by SirBlueAxolotl** [comment]
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/8790139/Latest.log)

**Comment by doombubbles** [comment]
From that log it would appear to be an error caused by one of your other mods. In the log it says the exceptions are coming from someone's patch of the UpdateIcon method of the StandardTowerPurchaseButton class, but Mod Helper doesn't add a patch there. I'd recommend trying different combinations of mods until it works so you can figure out the real culprit.

**Comment by SirBlueAxolotl** [comment]
How do I test if it works without having to wait 2 minutes

**Comment by SirBlueAxolotl** [comment]
Thank you
