### ISSUE TITLE
mods are not working

### ISSUE THREAD

**Issue by bendymgodman** [gurrenm3/BTD-Mod-Helper#38]
![Screenshot 2022-05-24 173450](https://user-images.githubusercontent.com/106197048/170136355-8da9dbe7-4fd8-4ae1-bf4b-11da1095bd6f.png)

also make updated mod helper for v31.2 if you can if you don't know how to fix it

**Comment by doombubbles** [comment]
In this case the error appears to be coming from not extracting the downloaded zip file. You need to make sure "BloonsTD6 Mod Helper.dll" itself is in the mods folder.
