### ISSUE TITLE
Version 32.0 broke the game

### ISSUE THREAD

**Issue by SirBlueAxolotl** [gurrenm3/BTD-Mod-Helper#50]
Modded towers broke (Insta-Monkeys is an easy way to show all towers):
![Screenshot (1370)](https://user-images.githubusercontent.com/105134703/183156955-d8138c12-727f-482b-b0db-72943318dbae.png)

Mods:
![image](https://user-images.githubusercontent.com/105134703/183157324-3da37f99-3374-47d2-a1ca-dc3ea7079f9a.png)

Crosspath & More paragons broke:
![Screenshot (1372)](https://user-images.githubusercontent.com/105134703/183256358-b5de9161-d5dc-433b-b01c-715c72b740b4.png)

**Comment by doombubbles** [comment]
Re-open if your problems haven't been fixed with 3.0.0 https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.0.0
