### ISSUE TITLE
Contested territories are broken

### ISSUE THREAD

**Issue by SirBlueAxolotl** [gurrenm3/BTD-Mod-Helper#51]
Contested territories broke:
![Screenshot (1369)](https://user-images.githubusercontent.com/105134703/183156774-ca6dda1b-40e5-4a29-b923-4d56d380dbe1.png)

**Comment by GooUckd** [comment]
It's because your using modded. Take the files away from the folder then you can play again.

**Comment by BtdIscool** [comment]
Your account is flagged reach out to ninja kiwi
