### ISSUE TITLE
my btd6 wont open

### ISSUE THREAD

**Issue by miguelcsgt** [gurrenm3/BTD-Mod-Helper#64]
everytime i try to open bloons melon loaader opens but bloons open with just this white screen then immeadiatly closes 
![image](https://user-images.githubusercontent.com/105379888/186447381-2faac0ec-27f7-4361-808e-6417768c5220.png)

**Comment by doombubbles** [comment]
Sounds like an issue with one of your mods. Can you send a screenshot of your Mods folder and upload your "BloonsTD6\MelonLoader\Latest.log" file?

**Comment by Tm641** [comment]
It happens to me too but I only have helper in my mods

**Comment by doombubbles** [comment]
https://discord.gg/9RXCaHKEQM ask in the discord if this was never resolved for you
