### ISSUE TITLE
Warning Error upon game launch

### ISSUE THREAD

**Issue by AelinDawntreader** [gurrenm3/BTD-Mod-Helper#70]
So, i've downloaded the modhelper and the 0.5.5 melon loader but when i boot the game i get "[BloonsTD6_Mod_Helper] [WARNING] Failed to apply BloonsTD6 Mod Helper patch(es) in HeroUpgradeDetails_BindDetails: "Patching exception in method null" alongside a bunch of red system text. The mod might not function correctly. This needs to be fixed by Gurrenm4 and Doombubbles" upon launching BTD6. I guess it's something to do with the mod itself and not something i've overlooked upon installing the mod stuff?

**Comment by ElectroIsFat** [comment]
can you send link to melon loader 0.5.5 i only see 0.5.4 on there github as the latest
