### ISSUE TITLE
mod helper dosen't work

### ISSUE THREAD

**Issue by tomegame** [gurrenm3/BTD-Mod-Helper#74]
Litteraly when starting something isnt working and theres no mods working or mod finder

**Comment by Toyqq** [comment]
I reinstalled melon loader, and it seemed to fix the issues.

**Comment by tomegame** [comment]
reinstalled and still dont work, there is problem with mod helper not with launcher

**Comment by notpoiu** [comment]
can you send a screenshot of what you are seeing, if possible a video?

**Comment by tomegame** [comment]
nah i dont need it now i fixed it

**Comment by notpoiu** [comment]
ok
