### ISSUE TITLE
it wont update.

### ISSUE THREAD

**Issue by Dark-king445** [gurrenm3/BTD-Mod-Helper#78]
so i had got this mod a year ago and i had left my game of for a week and now the mod wont show up or update. does anyone have any ideas to fix this?
all my mods don't work anymore.

**Comment by doombubbles** [comment]
For stuff that old you may want to save your self the head ache and just start from scratch. You can follow the newer [install guide](https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Install-Guide), with the most important steps being getting MelonLoader 0.5.5 and the latest version of Mod Helper. From there you can get up to date mods from the in game mod browser.
