### ISSUE TITLE
Mod Helper disappearing upon update, mods unusable

### ISSUE THREAD

**Issue by DynamicalGitHub** [gurrenm3/BTD-Mod-Helper#81]
[MelonLoader_22-11-03_19-36-51.730.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/9933760/MelonLoader_22-11-03_19-36-51.730.log)

**Comment by doombubbles** [comment]
You likely just need to reinstall MelonLoader through the official installer https://melonwiki.xyz/#/?id=automated-installation
