### ISSUE TITLE
Wiki doesn't clearly state how to define the bloons in a custom round set's round.

### ISSUE THREAD

**Issue by b-0-x-3-d** [gurrenm3/BTD-Mod-Helper#82]
as the title says

**Comment by doombubbles** [comment]
Added some examples to better illustrate the listed tip of "Use the Mod Helper's [extension methods](https://github.com/gurrenm3/BTD-Mod-Helper/blob/3.0_Features/Documentation/BTD_Mod_Helper.Extensions.RoundModelExt.md) for `RoundModel`s"
