### ISSUE TITLE
Using the existing tower 3d model method for TowerDisplays results in an error.

### ISSUE THREAD

**Issue by b-0-x-3-d** [gurrenm3/BTD-Mod-Helper#84]
`public override string BaseDisplay => Game.instance.model.GetTower(TowerType.DartMonkey).display;`
this is exactly the way that https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Custom-Textures-and-Displays says to do it but it results in the error of

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'Assets.Scripts.Utils.PrefabReference' to 'string'	Funni	C:\Users\boxed\OneDrive\Documents\BTD6 Mod Sources\Funni\Funni.cs	287	Active

**Comment by TheMegax** [comment]
That way of referencing existing tower displays is deprecated, use
`public override string BaseTower => TowerType.[towername];`

**Comment by b-0-x-3-d** [comment]
consider that being in documentation then ig
