### ISSUE TITLE
Centralized save data system

### ISSUE THREAD

**Issue by TheMegax** [gurrenm3/BTD-Mod-Helper#85]
The current mod settings system works great for storing -well- settings, but there's no built-in system for storing other types of data (e.g. in-game data, internal variables, player input, etc). Could it be possible to use the current json serializer for this save data?

**Comment by doombubbles** [comment]
Well, better late than never, version 3.1.7 will add `BloonsMod.OnSaveSettings(JObject settings)` and `BloonsMod.OnLoadSetings(JObject settings)` hooks that let you interact with the json
