### ISSUE TITLE
Crashes When I Hit Start

### ISSUE THREAD

**Issue by Kiwipheonix145** [gurrenm3/BTD-Mod-Helper#9]
Whenever I Hit Start On Any Map, It Just Crashes The Game.

**Comment by Kiwipheonix145** [comment]
Its Caused By Something In The .ddl Because Thats What Makes It Crash

**Comment by gurrenm3** [comment]
We've released a couple updates since you posted this issue. Can you confirm whether or not this issue is still happening?

**Comment by ScienceBoy908** [comment]
its crashing for me too.

**Comment by gurrenm3** [comment]
Are you using the latest version? Also when is it crashing?

**Comment by ScienceBoy908** [comment]
what version is that

**Comment by gurrenm3** [comment]
Latest version of the Mod Helper was released this morning, it's 2.3.1

**Comment by ScienceBoy908** [comment]
how do i get the version of the mod that does not crash

**Comment by gurrenm3** [comment]
https://github.com/gurrenm3/BTD-Mod-Helper/releases/latest

**Comment by ScienceBoy908** [comment]
thanks

**Comment by Kiwipheonix145** [comment]
I can't do it rn I'm on vacation give me about 4 - 5 days

**Comment by MrInfraRage** [comment]
it is still crashing for me

**Comment by gurrenm3** [comment]
Which version are you using? Also are you using any other mods?

**Comment by ChickfilaSauce1227** [comment]
Im using other mods that need to have mod helper and my mod helper wont update, please help!

**Comment by gurrenm3** [comment]
The other mods may be why you're experiencing issues. As mentioned in this message, you can download the latest release here:
> https://github.com/gurrenm3/BTD-Mod-Helper/releases/latest

**Comment by ChickfilaSauce1227** [comment]
Is there a certain button that I press to update the mod?

**Comment by gurrenm3** [comment]
This issue is closed because it looks like general mod help
