### ISSUE TITLE
New V34 Mod Helper Issue

### ISSUE THREAD

**Issue by Txmbry** [gurrenm3/BTD-Mod-Helper#95]
I'm not sure if I did something wrong but the game won't even launch, I've downloaded the new mod helper and nothing else is in the mod folder, and every time I launch the game it crashes.

**Comment by Jad3112** [comment]
same

**Comment by kai481** [comment]
I have the same problem, game crashes after opening and the console is full of red before crashing, I have the game from epic games, I would've post the log but I don't know where to find it

**Comment by doombubbles** [comment]
Modding on the epic games version is not yet officially supported
