### ISSUE TITLE
melonloader says uncompatible

### ISSUE THREAD

**Issue by stevencuhh** [gurrenm3/BTD-Mod-Helper#97]
Says "BloonsTD6 Mod Helper v3.1.0' is incompatible:BloonsTD6 Mod Helper is only compatible with the following Games: 'BloonsTD6' by Ninja Kiwi". im using epic games mod compat so that might be the issue but idk what i can do

**Comment by doombubbles** [comment]
Yeah this sounds like an issue with the epic games compat, which I'm not versed in, you may need to update it or something https://github.com/Baydock/BTD6EpicGamesModCompat
