### ISSUE TITLE
cant load btd mod helper

### ISSUE THREAD

**Issue by tactfulpuppet** [gurrenm3/BTD-Mod-Helper#98]
it says exactly this in melon loader: "Could not load signature of BTD_Mod_Helper.BloonsTD6Mod:ActOnMessage due to: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>" 
i dont know if this is a me problem or if its just because the btd mod helper hasnt been updated to the newest version.

**Comment by doombubbles** [comment]
Double check that you're using the official MelonLoader 0.6.0 and the latest Mod Helper 3.1.1
