### ISSUE TITLE
Doesn't open BTD6

### ISSUE THREAD

**Issue by Jtalk2018** [gurrenm3/BTD-Mod-Helper#99]
![image](https://user-images.githubusercontent.com/97309811/209869829-f355a13c-7f2a-4473-b6fd-3de271d5b02c.png)
This happens if I try to open BTD6

Also, 
![image](https://user-images.githubusercontent.com/97309811/209870020-49734830-620e-4469-a9ff-c902ed64ec57.png)
It says that v0.5.7 is the latest version

Oh wait that's not a problem with this specifically

Nvm it works without this but with this it just closes before it opens the title screen

**Comment by rakosi2** [comment]
In the installer, go to settings and enable ALPHA builds and install ML 0.6.0

**Comment by doombubbles** [comment]
https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Switching-to-MelonLoader-0.6.0

**Comment by Jtalk2018** [comment]
Sorry guys forgot to tell you that I got it to work. Thanks anyway!
